# Generated by Django 5.1.4 on 2025-02-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='emails',
            new_name='email',
        ),
    ]
